default_language_version:
  python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ["--line-length=79"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=E402,E501,E203,W503"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        args: [--strict]
        stages: [manual]

-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
    -   id: poetry-check
    -   id: poetry-lock

-   repo: local
    hooks:
    -   id: unittests
        name: run unit tests
        entry: poetry run test
        language: system
        pass_filenames: false
        stages: [manual]
