[tool.poetry]
name = "scanner"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.scripts]
scanner = "scanner.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.2.2"

# extractors dependencies
pefile = "^2022.5.30"
pdbparse = "^1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
