[tool.poetry]
name = "scanner"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.scripts]
scanner = "scanner.__main__:main"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.2.2"

# extractors dependencies
pefile = "^2022.5.30"
pdbparse = "^1.5"
lief = "^0.12.3"
pandas = "^1.5.2"
scikit-learn = "^1.2.0"
joblib = "^1.2.0"
seaborn = "0.11"
numpy = "^1.24.0"
uvloop = "^0.17.0"

[tool.poetry.dev-dependencies]
types-Flask = "^1.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
